services:
  - type: web
    name: mr-khan-project
    runtime: python
    rootDir: ml
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NVIDIA_STT_API_KEY
        sync: false
      - key: NVIDIA_TTS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
